source 'https://rubygems.org'

ruby '2.4.0'

  gem 'bcrypt'
  gem 'capybara'
  gem 'data_mapper'
  gem 'dm-postgres-adapter'
  gem 'dm-migrations'
  gem 'dm-transactions'
  gem 'sinatra'
  gem 'rack'
  gem 'rspec'
  gem 'rake'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'rubocop'
  gem 'database_cleaner'
